##
## Makefile for lkm-ourmb**
##
## Originally made by xsyann
## Contact <contact@xsyann.com>
##
## Current version -1 built by Yuan Xiao
## Contact <xiao.465@osu.edu>
##
## Current version built by Scott Thomas, Jiacheng Liu, Quinn Wu
##


all:
	cd lkm; make
	cd test; make

clean:
	cd lkm; make clean
	cd test; make clean
